<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operations [
        <!ELEMENT operations (operation)+>
        <!ELEMENT operation (set)+>
        <!ATTLIST operation
                name CDATA #REQUIRED>
        <!ELEMENT set (ins)+>
        <!ELEMENT ins (reg1|reg2)*>
        <!ATTLIST ins
                mnemonic CDATA #REQUIRED>
        <!ELEMENT reg1 (#PCDATA)>
        <!ATTLIST reg1
                value CDATA #IMPLIED>
        <!ELEMENT reg2 (#PCDATA)>
        <!ATTLIST reg2
                value CDATA #IMPLIED>
        ]>
<operations>
    <operation name="lc">
        <set>
            <ins mnemonic="pop">
                <reg1>dst</reg1>
            </ins>
        </set>
        <set>
            <ins mnemonic="popad"/>
        </set>
    </operation>
    <operation name="move">
        <set>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="add">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="and">
                <reg1 value="0xFFFFFFFF">dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="not">
                <reg1>dst</reg1>
            </ins>
            <ins mnemonic="and">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="stc"/>
            <ins mnemonic="adc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>aux</reg1>
            </ins>
            <ins mnemonic="adc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="clc"/>
            <ins mnemonic="cmovnc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>aux</reg1>
            </ins>
            <ins mnemonic="cmovc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="neg">
                <reg1 value="0xFFFFFFFF">aux</reg1>
            </ins>
            <ins mnemonic="cmovc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="stc"/>
            <ins mnemonic="cmovc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="mov">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="push">
                <reg1>src</reg1>
            </ins>
            <ins mnemonic="pop">
                <reg1>dst</reg1>
            </ins>
        </set>
        <set>
            <ins mnemonic="xchg">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>eax</reg1>
                <reg2>eax</reg2>
            </ins>
            <ins mnemonic="inc">
                <reg1>eax</reg1>
            </ins>
            <ins mnemonic="mul">
                <reg1>dst</reg1>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>src</reg1>
                <reg2>src</reg2>
            </ins>
            <ins mnemonic="xadd">
                <reg1>src</reg1>
                <reg2>dst</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>src</reg1>
            </ins>
            <ins mnemonic="sub">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="load">
        <set>
            <ins mnemonic="mov">
                <reg1>dst</reg1>
                <reg2>[src]</reg2>
            </ins>
        </set>
    </operation>
    <operation name="store">
        <set>
            <ins mnemonic="mov">
                <reg1>[dst]</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="add">
        <set>
            <ins mnemonic="add">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="clc"/>
            <ins mnemonic="adc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>aux</reg1>
            </ins>
            <ins mnemonic="adc">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="sub">
        <set>
            <ins mnemonic="sub">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="clc"/>
            <ins mnemonic="sbb">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>aux</reg1>
            </ins>
            <ins mnemonic="sbb">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="and">
        <set>
            <ins mnemonic="and">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="or">
        <set>
            <ins mnemonic="or">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="xor">
        <set>
            <ins mnemonic="xor">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="not">
        <set>
            <ins mnemonic="not">
                <reg1>dst</reg1>
            </ins>
        </set>
        <set>
            <ins mnemonic="xor">
                <reg1 value="0xFFFFFFFF">dst</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
    <operation name="cond1">
        <set>
            <ins mnemonic="sub">
                <reg1>dst</reg1>
                <reg2>src</reg2>
            </ins>
            <ins mnemonic="xor">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="adc">
                <reg1>aux</reg1>
                <reg2>aux</reg2>
            </ins>
            <ins mnemonic="neg">
                <reg1>aux</reg1>
            </ins>
        </set>
    </operation>
    <operation name="cond2">
        <set>
            <ins mnemonic="pop">
                <reg1>dst</reg1>
            </ins>
            <ins mnemonic="and">
                <reg1>src</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="add">
                <reg1>esp</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="pop">
                <reg1>dst</reg1>
            </ins>
            <ins mnemonic="and">
                <reg1>src</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="add">
                <reg1>src</reg1>
                <reg2>esp</reg2>
            </ins>
            <ins mnemonic="mov">
                <reg1>esp</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
        <set>
            <ins mnemonic="pop">
                <reg1>dst</reg1>
            </ins>
            <ins mnemonic="and">
                <reg1>src</reg1>
                <reg2>dst</reg2>
            </ins>
            <ins mnemonic="add">
                <reg1>src</reg1>
                <reg2>esp</reg2>
            </ins>
            <ins mnemonic="xchg">
                <reg1>esp</reg1>
                <reg2>src</reg2>
            </ins>
        </set>
    </operation>
</operations>